In [2]:
import numpy as np

In [3]:
x=np.array([2,4,5,6,7,8,9])
x[[-1,0]]

array([9, 2])

In [4]:
x>5

array([False, False, False,  True,  True,  True,  True])

In [5]:
(x>5).sum()

4

In [6]:
x

array([2, 4, 5, 6, 7, 8, 9])

In [7]:
t=x==2
t.any()

True

In [8]:
p=x%2==0
p.any()

True

In [9]:
x

array([2, 4, 5, 6, 7, 8, 9])

In [10]:
o=x<10
o.all()

True

In [11]:
five=x<5
five=five.all()
five

False

In [12]:
jungle=np.array(["lion","horse","lion","cat","Dog"])
jungle

array(['lion', 'horse', 'lion', 'cat', 'Dog'], dtype='<U5')

In [13]:
lion=jungle=="lion"
lion.sum()


2

In [14]:
donkey=jungle=="donkey"
donkey.any()

False

In [15]:
x

array([2, 4, 5, 6, 7, 8, 9])

In [16]:
np.unique(jungle)

array(['Dog', 'cat', 'horse', 'lion'], dtype='<U5')

In [17]:
np.save("data.npy",jungle)


In [19]:
r=np.random.randn(10,10)
print(r)

[[ 0.37494038 -0.00570859 -0.79708687 -0.02270796 -1.32839451  0.15397554
   0.94514387  0.3135584   0.72622575 -0.26209584]
 [-0.45069975 -1.06641047  0.89213236 -0.61822653 -0.99944179 -0.85631556
   2.27630593 -1.67534381 -0.76537416 -0.88899406]
 [-0.51043758  0.68978391  1.1170503  -0.85164686  0.94398863 -2.00187442
   1.42904311  0.72908272 -0.46378597 -1.90469896]
 [ 0.42324934 -1.74100337  0.06150336 -0.16713279 -2.47267304  0.98478978
   0.76603089 -2.79968448  0.66487586 -0.66847352]
 [ 0.51245198  1.74841307 -0.96768154  0.62643295 -0.00514828  0.20865859
   0.12807853  0.53752083  1.42350428  0.07253197]
 [-0.70058935  0.56433865 -1.08074465  0.57045365  0.76509134 -0.50511953
  -1.12478298  1.82586913  0.56601956  0.76794399]
 [-2.78771967  0.94912516 -0.18495865 -1.56483774 -0.35426761  0.53733347
  -0.23399532  2.04249482 -0.73642777 -0.9449251 ]
 [ 1.85619233 -0.21654753 -1.76538381 -0.01893802  0.44912657  0.36079582
   0.53566045  0.68175346 -0.90041265 -0.3557172 ]


In [24]:
np.save("randomN.npy",r)


In [25]:
sa=np.load("randomN.npy")
sa.shape

(10, 10)

In [28]:
p=np.random.randn(5,5)

In [29]:
np.savez("multi.npz",al=r,a2=p)


In [30]:
d=np.load("multi.npz")
d["al"]

array([[ 0.37494038, -0.00570859, -0.79708687, -0.02270796, -1.32839451,
         0.15397554,  0.94514387,  0.3135584 ,  0.72622575, -0.26209584],
       [-0.45069975, -1.06641047,  0.89213236, -0.61822653, -0.99944179,
        -0.85631556,  2.27630593, -1.67534381, -0.76537416, -0.88899406],
       [-0.51043758,  0.68978391,  1.1170503 , -0.85164686,  0.94398863,
        -2.00187442,  1.42904311,  0.72908272, -0.46378597, -1.90469896],
       [ 0.42324934, -1.74100337,  0.06150336, -0.16713279, -2.47267304,
         0.98478978,  0.76603089, -2.79968448,  0.66487586, -0.66847352],
       [ 0.51245198,  1.74841307, -0.96768154,  0.62643295, -0.00514828,
         0.20865859,  0.12807853,  0.53752083,  1.42350428,  0.07253197],
       [-0.70058935,  0.56433865, -1.08074465,  0.57045365,  0.76509134,
        -0.50511953, -1.12478298,  1.82586913,  0.56601956,  0.76794399],
       [-2.78771967,  0.94912516, -0.18495865, -1.56483774, -0.35426761,
         0.53733347, -0.23399532,  2.04249482

In [31]:
a=np.arange(1,11).reshape(5,2)
b=np.arange(2,11,2)
c=np.arange(0,11,3)
np.savez("multi.npz",al=a,a2=b,a3=c)

In [32]:
d=np.load("multi.npz")
d["al"]

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
d=np.load("multi.npz")
d["a2"]

array([ 2,  4,  6,  8, 10])

In [37]:
d=np.load("multi.npz")
d["a3"]

array([0, 3, 6, 9])